//#define TRACKING_LOST 4
//#define SYSTEM_NOT_READY -1
//#define NO_IMAGE_YET 0
//#define NOT_INITIALIZED 1
//#define INITIALIZING 2
//#define WORKING 3

enum ERROR_CODE
{
 TRACKING_LOST = 4,
 SYSTEM_NOT_READY = -1,
 NO_IMAGE_YET = 0,
 NOT_INITIALIZED = 1,
 INITIALIZING = 2,
 WORKING = 3,
 CAMERA_OPEN_FAILED = 4,
 WRONG_VOCFILE_PATH = 5,
 WRONG_SETTING_FILE_PATH = 6,
 UNSPECIFIC_ERROR = 7
};