
// Alan Zhang
// 2016.9.1

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_orb_slam2_android_alan_NativeLoaderORB */

#ifndef _Included_com_example_orb_slam2_android_alan_NativeLoaderORB
#define _Included_com_example_orb_slam2_android_alan_NativeLoaderORB
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jfloatArray JNICALL Java_com_example_orb_1slam2_1android_1alan_NativeLoaderORB_getRTfromSLAM
	(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_example_orb_1slam2_1android_1alan_NativeLoaderORB_runSLAM_1Alan
	(JNIEnv *env, jobject obj, jlong inputImage);

#ifdef __cplusplus
}
#endif
#endif
